# Generated by Django 5.2.17 on 2026-08-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the order was approved by an admin', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the order was rejected by an admin', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current lifecycle status of the order', max_length=20),
        ),
    ]
