# Generated by Django 5.2.17 on 2026-08-25 08:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('sku', models.CharField(db_index=True, help_text='Unique Stock Keeping Unit', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price in currency units. Must be greater than 0.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available stock quantity. Must be 0 or greater.', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this product is active (soft-delete flag).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
